[Javascript] Add naturaljs
the-benchmarker/web-frameworks pull request #3327
Opened 2020-09-19 02:08 UTC by jesusvilla

Add naturaljs #3301

2020-09-21 12:16 UTC, waghanza requested changes

2020-09-21 13:44 UTC, jesusvilla commented on javascript/naturaljs-router/package.json
> +    "natural-framework": "^0.1.1"
done

2020-09-21 13:45 UTC, jesusvilla commented on javascript/naturaljs-router/app.js
> +    console.log(`Listen http://localhost:${port}`)
@waghanza done

2020-09-22 16:43 UTC, jesusvilla commented
@waghanza, I already made the changes you requested

2020-09-24 07:13 UTC, waghanza approved these changes
Thanks for your contribution. I can give you any date for fresh results, but be sure I'm working on it ❤️

2020-09-24 07:14 UTC, merged