Add R `plumber` and `httpuv`
the-benchmarker/web-frameworks pull request #3334
Opened 2020-09-22 21:05 UTC by schloerke

Fixes https://github.com/the-benchmarker/web-frameworks/issues/3303

Updates:
* Adds `r.plumber` framework
* Adds `r.httpuv` framework

---------------

Commands used to tests locally on macOS:

```bash
# install
brew install crystal wrk postgresql docker-machine
/usr/local/opt/postgres/bin/createuser -s postgres

# set up docker
docker-machine rm default --force
docker-machine create default
eval $(docker-machine env default) 

# build
shards build
bin/make config --driver docker-machine

# set up database
export DATABASE_URL=postgresql://postgres@localhost/benchmark
dropdb -U postgres benchmark
createdb -U postgres benchmark
psql -U postgres -d benchmark < .ci/dump.sql

# test
bin/neph r --seq 

# save output
bin/db to_readme
```

Relevant local test output:
|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) |
|----|----------|-----------|-----------:|------------:|------------:|
| 1 | r (4.0)| [httpuv](https://https://github.com/rstudio/httpuv/) (1.5.4) | 987 | 1 012 | 835 |
| 2 | r (4.0)| [plumber](https://rplumber.io) (1.0.0) | 223 | 240 | 229 |
| 3 | r (4.0)| [restrserve](https://restrserve.org) (0.3) | 125 | 103 | 37 |

------------

cc @t-wojciech

2020-09-23 07:54 UTC, t-wojciech commented
Thanks for this PR. I am really surprised by the improved performance in the new version of `plumber` over `restrserve` in your local test. Good job!

2020-09-24 11:45 UTC, waghanza requested changes

2020-09-24 14:26 UTC, schloerke commented on r/httpuv/config.yaml
> +  website: https://github.com/rstudio/httpuv/
```suggestion
  github: rstudio/httpuv
```

2020-09-24 14:26 UTC, schloerke commented on r/httpuv/config.yaml
> +  version: 1.5.4
```suggestion
  version: 1.5
```

2020-09-24 14:26 UTC, schloerke commented on r/plumber/config.yaml
> +  version: 1.0.0
```suggestion
  version: 1.0
```

2020-09-25 16:47 UTC, merged

2020-09-28 14:45 UTC, vikram-rawat commented
Great results @schloerke ... could you also post a benchmark with serialization added. so that We can see how much difference there actually is. Just for reference. Please

2020-09-28 15:09 UTC, schloerke commented
@vikram-rawat The plumber results above contain the default behavior (currently using the 4 default filters and using the content-type serializer).

Plumber sits on top of `httpuv`, so we can think that the speed would be upper bounded by `httpuv`'s speed.  

In my local testing in #3303, I found that plumber could be 2x faster if the filters were removed but this did not represent the typical user interaction. To be a better representation of what plumber is, I kept the filters in. (But speeding up the filters is something to address and look forward to!)

2020-09-28 16:26 UTC, vikram-rawat commented
Trust me I never expected this speed from plumber package. Plumber 1.0 has now certainly piqued my interest. I am really amazed. 👍 🥇  

It's twice as fast as RestRserve. All I want to know if there is any optimization that I missed in the code. @dselivanov should actually look into it. I would really like to know the result. as I am currently finalizing an API framework for next project.

2020-09-28 17:05 UTC, schloerke commented
I believe this comes from the default behavior of each routing package. The `hello-world` style testing done by `web-frameworks` is better to be done using a single thread (ex: `httpuv`, which `plumber` wraps). There is too much overhead to process "each request in a separate fork" (ex: `RServe`, which `RestRServe` wraps) when only returning static values.

`RestRServe` (with no specialized route code) will handle long execution processes in parallel, therefore will handle many long execution processes faster when compared to the default single-threaded processing of `plumber`. However, in `plumber` v1.0.0 `promises` (ex: `future::future()`) is now supported. So the long processing time performance comparison (https://restrserve.org/articles/benchmarks/Benchmarks.html#comparison-with-plumber) should be re-evaluated under comparable execution conditions (ex: same number of parallel processing engines).

2020-09-28 17:16 UTC, dselivanov commented
@schloerke you are right! Would you consider to send PR for fair benchmark against plumber 1.0? 

Actually overhead for processing each request in a separate fork is not huge. The issue is that request handler is getting JIT compiled beforehand in each fresh fork (https://github.com/rexyai/RestRserve/issues/149) . This will be fixed in the next release.

2020-09-29 07:19 UTC, vikram-rawat commented
Thanks for the info guys... I would love to see both frameworks grow... We really need you 👍

2020-09-29 08:38 UTC, t-wojciech commented
Great discussion, thank you for your efforts and I wish you next success!