Add R/Rserve
the-benchmarker/web-frameworks pull request #3391
Opened 2020-10-28 18:11 UTC by artemklevtsov

2020-10-29 12:37 UTC, waghanza commented
Thanks @artemklevtsov.

@s-u do you consent, at least not opposed, to include https://github.com/s-u/Rserve in `here` ?

2020-11-05 11:09 UTC, s-u commented
@waghanza yes, thanks!

2020-11-05 13:40 UTC, waghanza requested changes

2020-11-05 13:40 UTC, waghanza commented on .travis.yml
>        - FRAMEWORK=fsharp.suave
could you remove this file ? no longer required with the new CI, but please you need to run `rake ci:config` before push

2020-11-05 13:40 UTC, waghanza commented on r/rserve/config.yaml
> +  version: 1.7-3
could you use `X.Y` format ?

2020-11-06 06:08 UTC, merged

2020-11-11 16:55 UTC, t-wojciech commented
@s-u There are already results from this benchmark and `Rserve` is doing quite well.

> Pos  | Language | Framework | Speed (64) | Speed (256) | Speed (512)
> 107 | r (4.0) | rserve (1.7) | 41 968 | 29 638 | 29 848