🐦[FSharp] Falco - v2.0.3
the-benchmarker/web-frameworks pull request #3395
Opened 2020-11-03 11:25 UTC by pimbrouwers

Upgrade to Falco v2.0.3

2020-11-06 08:45 UTC, waghanza commented
@pimbrouwers could you merge or rebase from master ? I've changed a lot of things

2020-11-06 09:46 UTC, pimbrouwers commented
More than happy to do that Marwan!

On Fri., Nov. 6, 2020, 3:45 a.m. Marwan Rabbâa, <notifications@github.com>
wrote:

> @pimbrouwers <https://github.com/pimbrouwers> could you merge or rebase
> from master ? I've changed a lot of things
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/the-benchmarker/web-frameworks/pull/3395#issuecomment-722955594>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDB57IZTKSVBNVFR6XFZ4LSOOZTTANCNFSM4TIT5EEQ>
> .
>

2020-11-07 11:44 UTC, pimbrouwers commented
@waghanza This should be good to go.

2020-11-07 12:38 UTC, waghanza requested changes

2020-11-07 12:38 UTC, waghanza commented on fsharp/falco/config.yaml
> +  version: 2.0.3
could you use `X.Y` form ?

2020-11-07 13:16 UTC, pimbrouwers commented
Done!

On Sat., Nov. 7, 2020, 7:38 a.m. Marwan Rabbâa, <notifications@github.com>
wrote:

> *@waghanza* requested changes on this pull request.
> ------------------------------
>
> In fsharp/falco/config.yaml
> <https://github.com/the-benchmarker/web-frameworks/pull/3395#discussion_r519173423>
> :
>
> > @@ -1,3 +1,3 @@
>  framework:
>    github: pimbrouwers/Falco
> -  version: 1.2
> +  version: 2.0.3
>
> could you use X.Y form ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/the-benchmarker/web-frameworks/pull/3395#pullrequestreview-525650273>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABDB57IDSODR4Z55K4MZM53SOU5TXANCNFSM4TIT5EEQ>
> .
>

2020-11-11 18:17 UTC, waghanza approved these changes

2020-11-11 18:18 UTC, merged

2020-11-15 22:15 UTC, pimbrouwers commented
See #3455