adding low-http-server
the-benchmarker/web-frameworks pull request #3575
Opened 2020-12-08 22:10 UTC by jkyberneees

Adding [low-http-server](https://github.com/jkyberneees/low-http-server) HTTP server implementation. Here we are using `0http` as routing layer.
> This implementation is also based on uWebSockets!

2020-12-09 09:07 UTC, waghanza commented
t LGTM @jkyberneees.

I'll merge this implementation with the `0http` in the future, btw

2020-12-09 09:23 UTC, jkyberneees commented
Thanks @waghanza, agreed!

2020-12-09 13:24 UTC, waghanza commented on javascript/low-http-server/config.yaml
> +  version: 2.1
you need to add

```yaml
build_deps:
  - git

bin_deps:
  - gcompat # required by uWebSocket
```
@jkyberneees 

to ensure compatibility with `alpine` **containers**

2020-12-09 14:22 UTC, waghanza requested changes

2020-12-09 14:22 UTC, waghanza commented on reviewers.yaml
> +  low-http-server:
👍

2020-12-10 08:47 UTC, waghanza approved these changes

2020-12-10 08:48 UTC, merged

2020-12-11 08:47 UTC, waghanza commented
Results are up-to-date @jkyberneees 

https://github.com/the-benchmarker/web-frameworks#results

2020-12-11 09:04 UTC, jkyberneees commented
Many thanks @waghanza, you rock!!!