[Java] Add vertx
the-benchmarker/web-frameworks pull request #3801
Opened 2021-01-19 06:42 UTC by waghanza

Hi,

This `PR` introduces vertx.

Regards,

-----------
@pmlopes @jponge Would you mind review this `PR` ?

-----------
Closes #441

2021-01-20 11:01 UTC, pmlopes requested changes
Overall this is a good start. In order to get the top performance, I'd recommend a few changes, mostly on the setup, not on the code itself.

Let me know if assistance is needed to get the changes in.

2021-01-20 11:01 UTC, pmlopes commented on java/vertx4web/src/main/java/benchmark/vertx4web/BenchmarkApplication.java
> +        router.get("/").respond( ctx -> ctx.response().setStatusCode(200).end());
No need to set status, it's set by default to 200.

2021-01-20 12:18 UTC, waghanza commented
Thanks for all your feedback @pmlopes. I must have told this before, the first purpose (for this project) is to reflect real-life usages. The idea is not to have the maximum performance, but a mix of :
+ Security
+ Safety
+ Scalability
+ Best-practices 
+ ...

It really depends on the community behind the framework.

2021-01-20 16:01 UTC, pmlopes commented
Ok in that case most of the startup flags I've listed can be ignored. I'll try to make a PR on the PR tomorrow so we can discuss it further.

2021-01-31 20:19 UTC, waghanza commented on java/vertx/pom.xml
> +                <artifactId>maven-compiler-plugin</artifactId>
I'm not sure how to do that @pmlopes

2021-02-04 20:42 UTC, waghanza commented
@pmlopes time to `PR` ?

2021-02-04 20:45 UTC, pmlopes commented
Hi, I've been busy with other tasks. I hope to get it ready tomorrow or beginning next week.

2021-02-04 20:47 UTC, waghanza commented
ok

I prefer that a professional `java` developer make this implementation 😛

2021-02-05 11:23 UTC, closed without merging