[PHP] Antidot: Enable multi-thread feature
the-benchmarker/web-frameworks pull request #3842
Opened 2021-01-24 18:16 UTC by kpicaza

I added support to run the framework using all available threads;-D. Also, I included a package that implements the application global middleware classes using promises. 

Thanks for your great work :clap::clap::clap:

2021-01-25 07:52 UTC, waghanza requested changes

2021-01-26 16:54 UTC, kpicaza commented on php/antidot/composer.json
>      "antidot-fw/framework": "~0.1.3",
Yes, we are working on a react-framework update, but is not yet ready.

2021-01-26 16:54 UTC, kpicaza commented on php/antidot/config/services/dependencies.prod.yaml
> +    max_concurrency: 512
max_concurrency is a config param passed to the react HTTP server, we use it to not saturate the server, the default value is 100

2021-01-26 16:55 UTC, kpicaza commented on php/antidot/config/services/dependencies.prod.yaml
> +    workers: 16
The "workers" config value, must be a number greater than 1 to load the required dependencies for multi-threading, In this case, I get dynamically the available number of threads using "nproc" function in in the index.php file(In standard installation it should be the "workers" value). 

Thanks for your review;-D

2021-01-26 19:09 UTC, waghanza approved these changes

2021-01-26 19:10 UTC, merged