Add swoole
the-benchmarker/web-frameworks pull request #3851
Opened 2021-01-25 10:24 UTC by hhxsv5

[Swoole](https://github.com/swoole/swoole-src) is the Coroutine-based concurrency library for PHP.

2021-01-25 10:26 UTC, waghanza commented on php/swoole/config.yaml
> +command: php bin/laravels start
?

2021-01-25 10:34 UTC, hhxsv5 commented on php/swoole/config.yaml
> +command: php bin/laravels start
Sorry for that, modified

2021-01-25 10:41 UTC, waghanza commented
Seems to be related to https://github.com/the-benchmarker/web-frameworks/discussions/3789

2021-01-25 10:45 UTC, sy-records commented
@waghanza Is the intention to add Swoole? If so, I have time to add a new one, as Swoole has multiple implementations

2021-01-25 11:01 UTC, waghanza commented
> @waghanza Is the intention to add Swoole?

yes. this break up my plans, but seems to be an amazing feature, hop other communities will join on this effort

2021-01-25 17:55 UTC, waghanza commented on php/swoole/composer.json
> +}
I suggest having the following manifest
```suggestion
{
  "require": {
    "ext-swoole": "~4.6.0",
  }
}
```
it ensure that we are in-sync with version in the doc

2021-01-25 18:03 UTC, waghanza commented on php/swoole/start.php
> +    'worker_num' => swoole_cpu_num() * 2,
please use the same config as existing (made by @sy-records), I need to find an easiest way to include them
```suggestion
   'worker_num' => swoole_cpu_num() * 2,
    'enable_coroutine' => false,
    'log_file' => '/dev/null',
    'log_level' => SWOOLE_LOG_ERROR,
```

2021-01-25 18:03 UTC, waghanza requested changes
minor changes, but thanks for this

2021-01-26 02:34 UTC, hhxsv5 commented
Modified, please review.

2021-01-26 02:36 UTC, sy-records requested changes

2021-01-26 02:36 UTC, sy-records commented on php/swoole/start.php
> +    'pid_file'         => storage_path('laravels.pid'),
Useless code

2021-01-26 03:09 UTC, hhxsv5 commented on php/swoole/start.php
> +    'pid_file'         => storage_path('laravels.pid'),
Fixed

2021-01-26 08:43 UTC, waghanza approved these changes

2021-01-26 08:44 UTC, merged