remove tokio from salvo dependencies
the-benchmarker/web-frameworks pull request #4058
Opened 2021-03-10 13:40 UTC by chrislearn

2021-03-10 14:41 UTC, waghanza requested changes
`Cargo.lock` is not needed

could you also update `config.yaml` with `salvo-rs/salvo` (since github repo has moved)

as I understand `tokio` is not needed, I don't understand the `tokio` usage described in https://salvo.rs/book/quick-start/hello_world/

2021-03-10 20:10 UTC, waghanza approved these changes

2021-03-10 20:10 UTC, merged

2021-03-11 20:55 UTC, chrislearn commented
@waghanza I think I just give a way to avoid add tokio to dependiences in final projects. but the truth is salvo and hyper are base on tokio.

2021-03-11 20:58 UTC, chrislearn commented
@waghanza is that possible to add Cargo. lock to git ignore file?