add nim.scorper
the-benchmarker/web-frameworks pull request #4368
Opened 2021-06-01 07:50 UTC by bung87

2021-06-01 08:18 UTC, waghanza requested changes
missng CI config :-) just use `bundle exec rake ci:config` and commit `.semaphore/*`

2021-06-01 08:18 UTC, waghanza commented on nim/scorper/config.yaml
> +  version: 1.0.7
could you please use `X.Y` format ? (this decrease maintenance tasks)

```suggestion
  version: 1.0
```

2021-06-01 08:18 UTC, waghanza commented on nim/scorper/server.nim
> +const address = "127.0.0.1:3000"
please use broadcast address (otherwise we could not connect to the app since inside a container)
```suggestion
const address = "0.0.0.0:3000"
```

2021-06-01 08:18 UTC, waghanza commented on nim/scorper/server.nimble
> +requires "scorper >= 1.0.7"
```suggestion
requires "scorper >= 1.0 & < 1.1"
```

2021-06-01 10:02 UTC, waghanza approved these changes

2021-06-01 10:05 UTC, waghanza commented
results will not be available right after merge @bung87

I'll update results for wednesday

2021-06-01 11:02 UTC, bung87 commented
hi, my server can't compile with `--threads:on` flag, I need remove it , I dont think other nim framework need it.

2021-06-01 11:27 UTC, waghanza commented
feel free to remove it, I'll ask someones if really necessary

2021-06-01 11:38 UTC, bung87 commented
I forgot `httpbeast` has multithreaded

2021-06-01 12:55 UTC, waghanza approved these changes

2021-06-01 16:41 UTC, merged

2021-06-02 15:38 UTC, bung87 commented
is there live result I can check?