Added masonite upgrade to version 4
the-benchmarker/web-frameworks pull request #4809
Opened 2021-11-07 19:00 UTC by josephmancuso

2021-11-15 09:26 UTC, waghanza commented
Is the line https://github.com/MasoniteFramework/masonite/blob/c67a06946eab03cebb0b6b45c1236bba41ae1f22/src/masonite/authorization/Gate.py#L2 correct ?

```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.9/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.9/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/src/app/wsgi.py", line 1, in <module>
    from masonite.foundation import Application, Kernel
  File "/usr/local/lib/python3.9/site-packages/masonite/foundation/__init__.py", line 2, in <module>
    from .Kernel import Kernel
  File "/usr/local/lib/python3.9/site-packages/masonite/foundation/Kernel.py", line 27, in <module>
    from ..tests.HttpTestResponse import HttpTestResponse
  File "/usr/local/lib/python3.9/site-packages/masonite/tests/__init__.py", line 1, in <module>
    from .TestCase import TestCase
  File "/usr/local/lib/python3.9/site-packages/masonite/tests/TestCase.py", line 10, in <module>
    from ..request import Request
  File "/usr/local/lib/python3.9/site-packages/masonite/request/__init__.py", line 1, in <module>
    from .request import Request
  File "/usr/local/lib/python3.9/site-packages/masonite/request/request.py", line 7, in <module>
    from ..authorization import AuthorizesRequest
  File "/usr/local/lib/python3.9/site-packages/masonite/authorization/__init__.py", line 2, in <module>
    from .Gate import Gate
  File "/usr/local/lib/python3.9/site-packages/masonite/authorization/Gate.py", line 2, in <module>
    from masoniteorm import Model
ModuleNotFoundError: No module named 'masoniteorm'
```

2021-12-26 15:21 UTC, josephmancuso commented
@waghanza masoniteorm was missing from requirements

2021-12-26 21:14 UTC, waghanza requested changes
When requesting `/`, I have the following error
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/masonite/foundation/response_handler.py", line 27, in response_handler
    application.resolve(provider.boot)
  File "/usr/local/lib/python3.9/site-packages/masonite/container/container.py", line 223, in resolve
    return obj(*objects)
  File "/usr/local/lib/python3.9/site-packages/masonite/providers/RouteProvider.py", line 21, in boot
    request = self.application.make("request")
  File "/usr/local/lib/python3.9/site-packages/masonite/container/container.py", line 105, in make
    raise MissingContainerBindingNotFound(
masonite.exceptions.exceptions.MissingContainerBindingNotFound: request key was not found in the container
```

2021-12-26 21:21 UTC, josephmancuso commented on python/masonite/requirements.txt
> +masonite-orm
No. Masonite-or is technically not required from Masonite anymore. Its a standalone ORM that is installed in default projects

2021-12-26 21:28 UTC, waghanza commented on python/masonite/requirements.txt
> +masonite-orm
what if I do not required any orm layer ? may I remove database configurations ?

2021-12-26 21:31 UTC, josephmancuso commented on python/masonite/requirements.txt
> +masonite-orm
Yes you can remove any references to a database

2021-12-26 21:33 UTC, josephmancuso commented on python/masonite/requirements.txt
> +masonite-orm
Actually I just checked the codebase and there is a reference to masoniteorm in the core code so maybe it is required actually

2021-12-26 21:37 UTC, waghanza commented on python/masonite/requirements.txt
> +masonite-orm
Ok, glad to help any project. I'll leave the reference in here for now

2021-12-26 22:32 UTC, waghanza commented
can you help on https://github.com/the-benchmarker/web-frameworks/pull/4809#pullrequestreview-840110666 @josephmancuso ?t

2021-12-26 22:32 UTC, closed without merging

2021-12-26 22:34 UTC, josephmancuso commented
review what? This should be closed in favor of #4961