[R] add ambiorix framework
the-benchmarker/web-frameworks pull request #5267
Opened 2022-04-10 18:35 UTC by JohnCoene

Added the ambiorix framework (R language)

2022-04-11 07:06 UTC, waghanza requested changes
minor change about config file

2022-04-11 07:06 UTC, waghanza commented on r/ambiorix/config.yaml
> +  version: 2.1.0
```suggestion
  version: 2.1
```

2022-04-11 14:16 UTC, JohnCoene commented
@waghanza I'm sorry, it's my own framework and I managed to mess this up.
Should be good for a re-run of github action

2022-04-12 07:46 UTC, merged

2022-04-14 07:02 UTC, waghanza commented
@JohnCoene et voila ... https://web-frameworks-benchmark.netlify.app/result?f=ambiorix

2022-04-14 07:11 UTC, JohnCoene commented
Thank you!