[Java/helidon]: first attemp at introducing Helidon
the-benchmarker/web-frameworks pull request #5658
Opened 2022-09-19 12:45 UTC by whiplash

2022-09-19 14:54 UTC, waghanza requested changes
when running app on container

```
Error: Unable to initialize main class web.helidon.Main
Caused by: java.lang.NoClassDefFoundError: io/helidon/media/common/MediaSupport
```

2022-09-19 14:54 UTC, waghanza commented on java/helidon/config.yaml
> +command: /usr/bin/java -XX:-RelaxAccessControlCheck -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/helidon.webserver.jar
`AggressiveOpts` does not exists anymore

2022-09-19 16:07 UTC, waghanza commented on java/helidon/config.yaml
> +  version: 3.0.1
```suggestion
  version: 3.0
```

2022-09-19 16:07 UTC, waghanza commented on java/helidon/pom.xml
> +        <version>3.0.1</version>
```suggestion
        <version>[3.0,3.1)</version>
```

2022-09-20 11:43 UTC, whiplash commented
not sure what's going on here

2022-09-20 12:03 UTC, waghanza commented
it run inside the first layer, seems to be something not copied between containes

2022-09-28 17:52 UTC, whiplash commented
anything I can try to fix this?

2022-09-28 18:12 UTC, waghanza commented
maybe creating a all-in-one jar, honestly not sure to remember the name, fatjar, uberjar ... the idea is to have one jar file without extra dependencies.

the jar is not working since some required library are not copied from build container

2022-09-28 18:27 UTC, whiplash commented
> the idea is to have one jar file 

this is what `mvn package` does

2022-09-28 21:04 UTC, waghanza commented
then this issue comes from `pom.xml`, I mean a class could not be found
`Caused by: java.lang.NoClassDefFoundError: io/helidon/media/common/MediaSupport`

try :
- bundle exec rake config
- cd java/helidon
- docker build . -f .Dockerfile -t test
- docker run -ti test ash
- /usr/bin/java -XX:-RelaxAccessControlCheck -XX:+UseNUMA -XX:+UseParallelGC -jar /opt/web/target/helidon.webserver.jar

2022-09-29 07:18 UTC, waghanza commented
still an error
```
Error: Unable to initialize main class web.helidon.Main
Caused by: java.lang.NoClassDefFoundError: io/helidon/media/common/MediaSupport
```

2022-09-29 07:48 UTC, whiplash commented
let's see if @tomas-langer or @barchetta can help

2022-09-29 15:17 UTC, barchetta commented
I pulled this PR and I can build and run the helidon application in a shell.  My hunch is you are not copying `target/libs` to your container image. 

Our default packaging consists of:

1. `target/application.jar`: this contains the application code and a `Class-Path` entry for runtime dependencies
2. `target/libs`: contains all runtime dependencies for the application as referenced by the jar's `Class-Path`

2022-09-29 22:20 UTC, barchetta commented
@whiplash we consider the uber-jar an anti-pattern as they are not Docker image friendly and they introduce complexities concerning merging of resources (like `META-INF/services/*`). 

Another thing to note is that we support packaging the application as a jlink runtime image.  I have verified that this works with this PR:

```
mvn clean install -Pjlink-image
target/helidon.webserver-jri/bin/start
```

In this case `target/helidon.webserver-jri` contains a custom Java Runtime Image, plus the application code, plus the runtime dependencies.

2022-09-30 07:42 UTC, whiplash commented
Thanks so much @barchetta. 

@waghanza we can `try` with this jlink runtime and see how it goes

2022-09-30 08:25 UTC, whiplash commented
@waghanza maybe we made it :)

2022-09-30 08:27 UTC, waghanza approved these changes

2022-09-30 08:27 UTC, merged