Create a libhv example project
the-benchmarker/web-frameworks pull request #5734
Opened 2022-10-12 09:39 UTC by leamus

libhv example project

2022-10-12 11:39 UTC, waghanza requested changes

2022-10-12 11:39 UTC, waghanza commented on cpp/libhv/main.cpp
> +    server.port = 8888;
```suggestion
    server.port = 3000;
```

2022-10-12 11:40 UTC, waghanza commented
is the server available from `0.0.0.0` ?

2022-10-12 12:13 UTC, leamus commented
yes

2022-10-12 15:59 UTC, waghanza commented
could you create all `cmake` manifest please ?

you can take inspiration from `drogon` in **cpp** folder

2022-10-13 00:11 UTC, leamus commented
OK~

2023-04-15 16:16 UTC, waghanza commented
@leamus do you wish to continue this PR ?

2023-04-16 15:24 UTC, closed without merging