add happyx
the-benchmarker/web-frameworks pull request #6357
Opened 2023-05-13 09:36 UTC by Ethosa

Repo: https://github.com/HapticX/happyx

2023-05-14 13:13 UTC, waghanza commented
Will include `happyx` for tomorrow.  does it mean it replace `akane` @Ethosa ?

2023-05-14 13:23 UTC, waghanza commented
There is a compilation error on container
```nim
  Building server/hpx using c backend
oserr.nim(95)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: /usr/src/app/src [OSError]
```
The dockerfile is
```dockerfile
FROM nimlang/nim:1.6.12-alpine

RUN apk update && \
    apk upgrade --no-cache

  RUN apk --no-cache add pcre-dev

WORKDIR /usr/src/app

COPY . ./

ENV PATH $PATH:/root/.nimble/bin

RUN nimble install -y

  RUN nim c  --define:usePcreHeader --passL: "/usr/lib/libpcre.a"  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim

FROM alpine

WORKDIR /usr/src/app

RUN apk update && \
    apk upgrade --no-cache

RUN apk --no-cache add openssl-dev pcre-dev

  COPY --from=0 /usr/src/app/server /usr/src/app/server

  CMD /usr/src/app/server
```

2023-05-14 13:23 UTC, Ethosa commented
> Will include happyx for tomorrow. does it mean it replace akane @Ethosa ?

`akane` is legacy 👀

I can delete `akane` and add commit for this PR 🔨

2023-05-14 13:27 UTC, Ethosa commented
> There is a compilation error on container

@waghanza 
How I can change dockerfile?

Need change
```dockerfile
RUN nimble install -y
```
to
```dockerfile
RUN nimble install -d -y
```

2023-05-14 13:34 UTC, waghanza commented
By setting `build_command: nimble install -d -y` in `config.yaml`, and I have
```nim
Installing happyx@0.15.1
   Building happyx/hpx using c backend
/tmp/nimble_1/githubcom_HapticXhappyx_0.15.1/src/happyx/private/cmpltime.nim(2, 3) Warning: imported and not used: 'strformat' [UnusedImport]
/tmp/nimble_1/githubcom_HapticXhappyx_0.15.1/src/happyx/ssg/server.nim(105, 1) Warning: use exitprocs.addExitProc; addQuitProc is deprecated [Deprecated]
/tmp/nimble_1/githubcom_HapticXhappyx_0.15.1/src/hpx.nim(415, 17) template/generic instantiation of `createThread` from here
/nim/lib/system/threads.nim(358, 50) template/generic instantiation of `threadProcWrapper` from here
/nim/lib/system/threads.nim(197, 27) template/generic instantiation of `threadProcWrapStackFrame` from here
/nim/lib/system/threads.nim(188, 27) template/generic instantiation of `threadProcWrapDispatch` from here
/nim/lib/system/threads.nim(171, 5) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
/tmp/nimble_1/githubcom_HapticXhappyx_0.15.1/src/hpx.nim(429, 8) template/generic instantiation of `serve` from here
/tmp/nimble_1/githubcom_HapticXhappyx_0.15.1/src/happyx/ssg/server.nim(358, 27) template/generic instantiation of `async` from here
/nim/lib/pure/asyncmacro.nim(42, 5) Warning: The bare except clause is deprecated; use `except CatchableError:` instead [BareExcept]
   Success: happyx installed successfully.
      Info: Dependency on cligen@any version already satisfied
  Verifying dependencies for cligen@1.6.4
      Info: Dependency on regex@any version already satisfied
  Verifying dependencies for regex@0.20.2
      Info: Dependency on unicodedb@>= 0.7.2 already satisfied
  Verifying dependencies for unicodedb@0.12.0
      Info: Dependency on httpx@any version already satisfied
  Verifying dependencies for httpx@0.3.6
      Info: Dependency on ioselectors@>= 0.1.6 already satisfied
  Verifying dependencies for ioselectors@0.1.8
      Info: Dependency on wepoll@>= 0.1.0 already satisfied
  Verifying dependencies for wepoll@0.1.0
      Info: Dependency on illwill@any version already satisfied
  Verifying dependencies for illwill@0.3.0
      Info: Dependency on nimja@any version already satisfied
  Verifying dependencies for nimja@0.8.7
      Info: Dependency on websocketx@any version already satisfied
  Verifying dependencies for websocketx@0.1.2
      Info: Dependency on ws@>= 0.4.3 already satisfied
  Verifying dependencies for ws@0.5.0
      Info: Dependency on httpx@>= 0.1.8 already satisfied
  Verifying dependencies for httpx@0.3.6
      Info: Dependency on ioselectors@>= 0.1.6 already satisfied
  Verifying dependencies for ioselectors@0.1.8
      Info: Dependency on wepoll@>= 0.1.0 already satisfied
  Verifying dependencies for wepoll@0.1.0
 Installing server@0.15.1
   Building server/hpx using c backend
oserr.nim(95)            raiseOSError
Error: unhandled exception: No such file or directory
Additional info: /usr/src/app/src [OSError]
       Tip: 219 messages have been suppressed, use --verbose to show them.
     Error: Build failed for package: server
        ... Execution failed with exit code 1
        ... Command: /nim/bin/nim c --colors:on --noNimblePath -d:release -d:NimblePkgVersion=0.15.1 --path:/root/.nimble/pkgs/cligen-1.6.4 --path:/root/.nimble/pkgs/unicodedb-0.12.0 --path:/root/.nimble/pkgs/regex-0.20.2 --path:/root/.nimble/pkgs/wepoll-0.1.0 --path:/root/.nimble/pkgs/ioselectors-0.1.8 --path:/root/.nimble/pkgs/httpx-0.3.6 --path:/root/.nimble/pkgs/illwill-0.3.0 --path:/root/.nimble/pkgs/nimja-0.8.7 --path:/root/.nimble/pkgs/ws-0.5.0 --path:/root/.nimble/pkgs/httpx-0.3.6 --path:/root/.nimble/pkgs/ioselectors-0.1.8 --path:/root/.nimble/pkgs/wepoll-0.1.0 --path:/root/.nimble/pkgs/websocketx-0.1.2 --path:/root/.nimble/pkgs/happyx-0.15.1 --path:/root/.nimble/pkgs/cligen-1.6.4 --path:/root/.nimble/pkgs/regex-0.20.2 --path:/root/.nimble/pkgs/unicodedb-0.12.0 --path:/root/.nimble/pkgs/httpx-0.3.6 --path:/root/.nimble/pkgs/ioselectors-0.1.8 --path:/root/.nimble/pkgs/wepoll-0.1.0 --path:/root/.nimble/pkgs/illwill-0.3.0 --path:/root/.nimble/pkgs/nimja-0.8.7 --path:/root/.nimble/pkgs/websocketx-0.1.2 --path:/root/.nimble/pkgs/ws-0.5.0 --path:/root/.nimble/pkgs/httpx-0.3.6 --path:/root/.nimble/pkgs/ioselectors-0.1.8 --path:/root/.nimble/pkgs/wepoll-0.1.0 --hints:off -o:/usr/src/app/hpx /usr/src/app/src/hpx.nim
The command '/bin/sh -c nimble install -y' returned a non-zero code: 1
```

2023-05-14 13:45 UTC, waghanza commented
sorry @Ethosa, mis-understood
1. Add `build_with: nimble install -d -y` to `conifg.yaml`
2. Replace `RUN nimble install -y` with `{{#build_with}}{{{.}}}{{/build_wth}}}` in `nim/Dockerfile`

2023-05-14 13:54 UTC, waghanza commented
Seems to work with `-d`. What is this switch for ? @Ethosa

2023-05-14 13:56 UTC, Ethosa commented
> What is this switch for ?

@waghanza 
This flag disables compilation and fetches only dependencies without compilation binaries (HappyX contains CLI binary file)

2023-05-14 13:57 UTC, Ethosa commented
Also `-d` is shortcut for `--depsOnly`

2023-05-14 13:57 UTC, waghanza requested changes
I induced you into errors, sorry

2023-05-14 13:57 UTC, waghanza commented on nim/Dockerfile
> +{{/build_wth}}
```suggestion
{{/build_with}}
```

2023-05-14 13:57 UTC, waghanza commented on nim/Dockerfile
> +{{/build_wth}}}
```suggestion
{{/build_with}}}
```

2023-05-14 13:59 UTC, waghanza commented
Useful for other `nim` **frameworks**, seems like interesting behavior for me facing production needs

2023-05-14 14:00 UTC, waghanza requested changes

2023-05-14 14:00 UTC, waghanza commented on nim/Dockerfile
> +{{/build_with}}
```suggestion
{{#build_with}}
  RUN {{{.}}}
{{/build_with}}
{{^build_with}}
  RUN nimble install -y
{{/build_with}}
```

2023-05-14 14:05 UTC, waghanza commented
Compilation is OK now, only implementation is not correct, some routes are not throwing expected result
https://github.com/the-benchmarker/web-frameworks/actions/runs/4972765750/jobs/8898179596?pr=6357#step:8:1

@Ethosa 

PS : I've pushed throw github UI

2023-05-14 14:12 UTC, waghanza commented on nim/happyx/config.yaml
> +  version: 0.15.1
```suggestion
  version: 0.15
```

2023-05-14 14:12 UTC, waghanza commented on nim/happyx/server.nimble
> +requires "happyx >= 0.15.1"
```suggestion
requires "happyx >= 0.15 & < 0.16"
```

2023-05-14 14:49 UTC, waghanza requested changes

2023-05-14 14:49 UTC, waghanza commented on nim/happyx/server.nim
> +  get "/user$id:int":
I think

```suggestion
  get "/user/$id:int":
```

2023-05-14 15:21 UTC, waghanza approved these changes

2023-05-14 15:21 UTC, merged

2023-05-15 05:04 UTC, waghanza commented
@Ethosa `happyx` has been included https://web-frameworks-benchmark.netlify.app/result?l=nim