add elysia
the-benchmarker/web-frameworks pull request #6422
Opened 2023-06-09 09:57 UTC by jim-king-2000

Add elysia(bun) to the benchmarks.

2023-06-09 11:09 UTC, waghanza commented
@SaltyAom we plan to add `elysia` in here. Are you not opposed on such a thing ?

2023-06-09 11:14 UTC, waghanza commented
@Yusuke we plan to introduce `hono` in here. Are you opposed in such a thing?

2023-06-09 11:15 UTC, waghanza commented
@bunsvr we are going to introduce `stric` in here. Are you opposed on such a thing?

2023-06-09 11:45 UTC, waghanza requested changes
Thanks for introducing `bun` @jim-king-2000. You will need to add
```yml
bun:
  command: bun run app.ts
```
in `javascript/config.yaml` and create a simple dockerfile as `javascript/bun.Dockerfile`
```dockerfile
FROM oven/bun:0.6

WORKDIR /usr/src/app

{{#files}}
  COPY '{{source}}' '{{target}}'
{{/files}}

RUN apt-get -qq update

{{#deps}}
  RUN apt-get -qy install {{{.}}}
{{/deps}}

{{#bootstrap}}
  RUN {{{.}}}
{{/bootstrap}}

{{#environment}}
  ENV {{{.}}}
{{/environment}}

{{#fixes}}
  RUN {{{.}}}
{{/fixes}}

CMD {{{command}}}
```

2023-06-09 11:45 UTC, waghanza commented on javascript/elysia/config.yaml
> +  version: 0.5.17
```suggestion
  version: 0.5
```

2023-06-09 11:45 UTC, waghanza commented on javascript/elysia/package.json
> +    "elysia": "^0.5.17"
```suggestion
    "elysia": "~0.5.17"
```

2023-06-09 11:45 UTC, waghanza commented on javascript/hono/config.yaml
> +  version: 3.2.5
```suggestion
  version: 3.2
```

2023-06-09 11:45 UTC, waghanza commented on javascript/hono/package.json
> +    "hono": "^3.2.5"
```suggestion
    "hono": "~3.2.5"
```

2023-06-09 11:45 UTC, waghanza commented on javascript/stricjs/config.yaml
> +  version: 3.0.2
```suggestion
  version: 3.0
```

2023-06-09 11:45 UTC, waghanza commented on javascript/stricjs/package.json
> +    "@stricjs/router": "^3.0.2"
```suggestion
    "@stricjs/router": "~3.0.2"
```

2023-06-09 14:44 UTC, jim-king-2000 commented
Update the pull request.

2023-06-09 14:54 UTC, waghanza commented
Thanks @jim-king-2000, let's way a bit before merge (if there is no opposition for any framework in this PR)

2023-06-09 15:03 UTC, jim-king-2000 commented
Looking forward to the benchmark result. :blush:

2023-06-11 09:35 UTC, waghanza commented
I'll include those project on next run (monday)

2023-06-11 11:47 UTC, waghanza approved these changes

2023-06-11 11:47 UTC, merged

2023-06-12 02:14 UTC, jim-king-2000 commented
Glad to see it has been merged. I could add more frameworks. May I send the PR directly in the future?

2023-06-12 07:05 UTC, waghanza commented
Sure. You can propose any framework you want, but please ping the author / core members to see if it is valuable to include it here

2023-06-12 07:13 UTC, waghanza commented
Those frameworks has been included https://web-frameworks-benchmark.netlify.app/result?f=hono,stricjs,elysia