add uwebsockets.js
the-benchmarker/web-frameworks pull request #6506
Opened 2023-07-13 04:43 UTC by jim-king-2000

I wanna add `uwebsockets.js` to the benchmarks since it defeats all of the other frameworks [here](https://github.com/SaltyAom/bun-http-framework-benchmark).

2023-07-13 05:04 UTC, jim-king-2000 commented
It seems that the npm here does not support `github:uNetworking/uWebSockets.js#v20.30.0`. Any idea?

2023-07-13 06:53 UTC, waghanza commented
>It seems that the npm here does not support github:uNetworking/uWebSockets.js#v20.30.0. Any idea?
`git` is not installed

however @jim-king-2000, the author of `uws` (@uNetworkingAB) does not want to be included in here
https://github.com/the-benchmarker/web-frameworks/issues/1064

2023-07-13 09:23 UTC, jim-king-2000 commented
> however @jim-king-2000, the author of uws (@uNetworkingAB) does not want to be included in here
https://github.com/the-benchmarker/web-frameworks/issues/1064

Could you please check it with him again? If he insists to not be included, we have to close this PR.

2023-07-13 11:25 UTC, waghanza commented
lets way about 10 days if no reaction and we will merge, but I'm sure he will :-)

2023-07-13 15:38 UTC, jim-king-2000 commented
> lets way about 10 days if no reaction and we will merge

Sure.

> but I'm sure he will :-)

That would be better.

2023-07-21 09:08 UTC, jim-king-2000 commented
Any update?

2023-07-22 08:32 UTC, waghanza requested changes
When running `pm2-runtime start app.js -i max` I have
```javascript
(node:27) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/usr/src/app/app.js:1
import { App } from 'uWebSockets.js';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
    at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
```

2023-07-22 08:32 UTC, waghanza commented on javascript/uwebsockets/app.js
> +app.listen(port, result => result && console.log('Listening to port ' + port));
can you remove this console.log ?

It could mess-up the results

2023-07-22 08:32 UTC, waghanza commented on javascript/uwebsockets/config.yaml
> +  version: 20.30.0
```suggestion
  version: 20.30

  engines:
    - uwebsockets
```

2023-07-22 14:37 UTC, jim-king-2000 commented
> When running `pm2-runtime start app.js -i max` I have
> 
> ```js
> (node:27) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
> (Use `node --trace-warnings ...` to show where the warning was created)
> /usr/src/app/app.js:1
> import { App } from 'uWebSockets.js';
> ^^^^^^
> SyntaxError: Cannot use import statement outside a module
>     at internalCompileFunction (node:internal/vm:73:18)
>     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
>     at Module._compile (node:internal/modules/cjs/loader:1220:27)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
>     at Module.load (node:internal/modules/cjs/loader:1119:32)
>     at Module._load (node:internal/modules/cjs/loader:960:12)
>     at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
>     at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
>     at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
>     at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
> ```

Change `app.js` to `app.mjs`.

2023-07-22 21:13 UTC, waghanza requested changes

2023-07-22 21:13 UTC, waghanza commented on javascript/uwebsockets/config.yaml
> +  version: 20.30
sorry
```suggestion
  version: '20.30'
```

2023-07-24 09:21 UTC, jim-king-2000 commented
Why did it still fail?

2023-07-26 03:01 UTC, jim-king-2000 commented
@waghanza Would you please take a look at it? What is the error message?

2023-07-26 08:37 UTC, waghanza commented
```javascript
(node:166) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/usr/src/app/app.js:1
import { App } from "uWebSockets.js";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1178:20)
    at Module._compile (node:internal/modules/cjs/loader:1220:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at /usr/local/lib/node_modules/pm2/lib/ProcessContainer.js:304:25
    at wrapper (/usr/local/lib/node_modules/pm2/node_modules/async/internal/once.js:12:16)
    at next (/usr/local/lib/node_modules/pm2/node_modules/async/waterfall.js:96:20)
    at /usr/local/lib/node_modules/pm2/node_modules/async/internal/onlyOnce.js:12:16
```

@jim-king-2000

2023-07-26 08:38 UTC, waghanza requested changes

2023-07-26 08:38 UTC, waghanza commented on javascript/uwebsockets/package.json
> +  }
```suggestion
  },
  "type": "module"
```

2023-07-26 09:41 UTC, jim-king-2000 commented
Success. What about the attitude of the author of `uws`?

2023-07-26 09:52 UTC, waghanza commented
We are going to include `uws` in here @uNetworkingAB

2023-07-28 15:14 UTC, jim-king-2000 commented
@waghanza Let's just do it. We could disable it if there is any concern from the author.

2023-07-28 16:08 UTC, sginiatulin commented
C++ version of uws will be more interesting than js :)

2023-07-28 19:05 UTC, cyrusmsk commented
I think adding C++ package is even more interesting than js

2023-07-28 20:20 UTC, waghanza commented
Be my guest @cyrusmsk

2023-07-28 20:20 UTC, waghanza approved these changes

2023-07-28 20:20 UTC, merged

2023-07-29 13:57 UTC, jim-king-2000 commented
> I think adding C++ package is even more interesting than js

Maybe I could try to add `uws` cpp.