Update `nim/happyx` version
the-benchmarker/web-frameworks pull request #6540
Opened 2023-07-22 15:10 UTC by Ethosa

`v1.7.0.` -> `v1.10.0`

2023-07-22 21:13 UTC, waghanza requested changes

2023-07-22 21:13 UTC, waghanza commented on nim/happyx/config.yaml
> +  version: 1.10
```suggestion
  version: '1.10'
```
otherwise it will show `1.1`

2023-07-23 02:32 UTC, Ethosa commented on nim/happyx/config.yaml
> +  version: 1.10
@waghanza please, see updates

2023-07-23 09:44 UTC, waghanza approved these changes

2023-07-23 09:44 UTC, merged