Add clojure Pedestal web framework
the-benchmarker/web-frameworks pull request #6612
Opened 2023-08-11 14:15 UTC by gicornachini

Add [Pedestal](https://github.com/pedestal/pedestal) web framework.

| HTTP   | Route       | Status code | Response body         | Done? |
| ------ | ----------- | ----------- | --------------------- | ------- |
| `GET`  | `/`         | `200`       | **Empty**             | ✅ |
| `GET`  | `/user/:id` | `200`       | **id** given as param | ✅ |
| `POST` | `/user`     | `200`       | **Empty** | ✅ |

2023-08-11 14:21 UTC, waghanza commented
Hey,

Thanks @gicornachini for this PR.

This will include `pedestal` for next run, on Monday.

@hlship Are you OK with such a thing ?

Regards,

2023-08-12 08:31 UTC, waghanza commented
can you provide an example @hlship ?

I am pretty confused about JVM dialects with the version on jdk to use
https://hub.docker.com/_/clojure/tags contains a lot of, and not sure which jdk could be supported by clojure

2023-08-12 08:35 UTC, waghanza requested changes

2023-08-12 08:35 UTC, waghanza commented on clojure/pedestal/config.yaml
> +command: java -Xms2G -server -Xmx2G -XX:+UseStringDeduplication -XX:+UseParallelGC -Dvertx.disableMetrics=true -Dvertx.threadChecks=false -Dvertx.disableContextTimings=true -Dvertx.disableTCCL=true -
```suggestion
  image: clojure:openjdk-11-lein-slim-buster

  build:
    - lein uberjar

  binaries:
    - target/the-benchmarker-pedestal-0.0.1-SNAPSHOT-standalone.jar

  command: java -Xms2G -server -Xmx2G -XX:+UseStringDeduplication -XX:+UseParallelGC -Dvertx.disableMetrics=true -Dvertx.threadChecks=false -Dvertx.disableContextTimings=true -Dvertx.disableTCCL=true -Dvertx.disableH2c=true -Dvertx.disableWebsockets=true -Dvertx.disableHttpHeadersValidation=true -Dvertx.flashPolicyHandler=false -Djava.net.preferIPv4Stack=true -jar target/the-benchmarker-pedestal-0.0.1-SNAPSHOT-standalone.jar 3000
```

2023-08-15 13:54 UTC, gicornachini commented
@waghanza Now I hope it will work, at least locally is running correctly with the docker container.

![image](https://github.com/the-benchmarker/web-frameworks/assets/8667478/17776c42-2238-4b2d-9120-9d68e39821b2)

2023-08-16 09:26 UTC, merged