Add a web framework for the Rust language
the-benchmarker/web-frameworks pull request #6641
Opened 2023-08-19 10:29 UTC by Jzow

CC [issues 72](https://github.com/wansenai/summer-boot/issues/72).

2023-08-20 06:56 UTC, waghanza requested changes
Maybe you miss some configuration in config.yaml, some yaml files must be uploaded to the container.

You can take inspiration from spring config file for static_files configuration

2023-08-20 09:57 UTC, Jzow commented
[spring config.yaml](https://github.com/the-benchmarker/web-frameworks/blob/master/java/spring/config.yaml) From a language perspective, they are different, and we currently need to do a lot of work here while scanning the configuration file

2023-08-20 11:49 UTC, waghanza commented
Sorry, you need to add
```yaml
files:
  - resources/**/*.yml
```
in config.yaml in order to load file onto container at compilation stage

2023-08-21 04:59 UTC, Jzow commented
> Sorry, you need to add
> 
> ```yaml
> files:
>   - resources/**/*.yml
> ```
> 
> in config.yaml in order to load file onto container at compilation stage

Understood, thanks

2023-08-21 05:46 UTC, waghanza requested changes

2023-08-21 05:46 UTC, waghanza commented on rust/summer-boot/config.yaml
> +    - resources/**/*.yml
```suggestion
    - src/resources/**/*.yml
```

2023-08-21 05:51 UTC, waghanza commented on rust/summer-boot/Cargo.toml
> +name = "summer-boot"
```suggestion
name = "server"
```

2023-08-21 05:54 UTC, waghanza reviewed
Could you unify compilation options for rust frameworks ?

2023-08-21 05:58 UTC, waghanza reviewed
Missing to implement GET on /user/:I'd that returns :id

2023-08-21 05:58 UTC, waghanza commented on rust/summer-boot/src/main.rs
> +#[summer_boot::get("/hello")]
```suggestion
#[summer_boot::get("/")]
#[summer_boot::post("/user")]
```

2023-08-21 05:58 UTC, waghanza commented on rust/summer-boot/src/main.rs
> +    Ok(format!("Hello, Summer Boot").into())
```suggestion
    Ok().into())
```

2023-08-21 06:31 UTC, Jzow commented
Okay, I'll make the changes later

2023-08-21 12:55 UTC, merged