feat(javascript): add Fiber
the-benchmarker/web-frameworks pull request #6775
Opened 2023-10-04 21:54 UTC by gabrielcursino

Please add a new JavaScript framework: [Fiber](https://github.com/ionited/fiber)

2023-10-05 04:32 UTC, waghanza commented on javascript/fiber/package.json
> +    "@ionited/fiber": "^0.2.1"
```suggestion
    "@ionited/fiber": "~0.2.1"
```

2023-10-05 04:32 UTC, waghanza commented on javascript/fiber/config.yaml
> +  version: 0.2.1
```suggestion
  version: 0.2
```

2023-10-05 07:08 UTC, waghanza reviewed
error since we use `alpine`
```javascript
Error: This version of uWS.js supports only Node.js LTS versions 16, 18 and 20 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/src/app/node_modules/uWebSockets.js/uws_linux_x64_108.node)
    at /usr/src/app/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/usr/src/app/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:101:39)
    at require (node:internal/modules/cjs/helpers:121:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@ionited/fiber/dist/app.js:4:26)
```

2023-10-05 15:03 UTC, gabrielcursino commented
How can i help?

I found this on Stack Overflow: https://stackoverflow.com/questions/66963068/docker-alpine-executable-binary-not-found-even-if-in-path

2023-10-05 18:39 UTC, waghanza commented
I think https://github.com/ionited/fiber/blob/3019f6b375a9432d2a7e53e7dda5ed173368f698/package.json#L29 is incorrect, you should declare
```json
"uWebSockets.js": "github:uNetworking/uWebSockets.js#v20.31.0"
```

2023-10-05 21:19 UTC, gabrielcursino commented
Hello @waghanza, i've updated the package!

2023-10-06 09:02 UTC, waghanza requested changes

2023-10-06 09:02 UTC, waghanza commented on javascript/fiber/config.yaml
> +  version: 0.2
```suggestion
  version: 0.2
  engines:
    - uwebsockets
```

2023-10-06 15:14 UTC, waghanza commented
I will update results for monday @gabrielcursino, better not to miss this train 😛

2023-10-06 15:53 UTC, waghanza approved these changes

2023-10-06 15:53 UTC, merged