Rails 7 config updates
the-benchmarker/web-frameworks pull request #6818
Opened 2023-10-12 17:07 UTC by crimson-knight

I noticed a dramatic drop in the req/s for Rails after the 7 -> 7.1 upgrade. So I've made a few changes:

Changes to the config.yml that effect the Docker configuration:
- Added `RAILS_ENV` as production just in case it the fallback to `RACK_ENV` wasn't working as expected.
- Decreased logging for production by setting `RAILS_LOG_LEVEL` to `fatal`. Reducing logging should make a significant difference.

In the `Rails` test:
- Inheriting from `ActionController::Base` makes the app perform more closely to how it would if it were rendering views, so I aligned the configuration in the `config/application.rb` to match that expectation.

In the new `Rails-api` test:
- Reset the controller to inherit from the `ActionController::API` so this omits the rendering modules that normally get included into the `ActionController::Base` class
- Added some suggested middleware deletions from Rack that aren't required with an API-only Rails app

This should give a much better picture for anyone trying to understand the differences between a normal Rails app and an API-only Rails app (or just the API version of their app if they use the `ActionController::API` for their API controller base.

2023-10-13 07:02 UTC, waghanza requested changes
Thanks for the changes 🎉 

I have the following (when booting)
```ruby
[304] Couldn't find Active Storage configuration in /usr/src/app/config/storage.yml
```

2023-10-17 12:38 UTC, crimson-knight commented on ruby/config.yaml
> +    RAILS_ENV: production
@waghanza this was based on feedback from a Rails core team member so we can rule out a regression, that's why I added this to both places

2023-10-17 12:38 UTC, crimson-knight commented on ruby/rails-api/config/environments/production.rb
> +  config.public_file_server.enabled = true
Yeah I had originally just skipped this because we don't use static files anywhere for anything so changing it wouldn't make a difference 🤷‍♂️

2023-10-17 12:43 UTC, crimson-knight commented on ruby/config.yaml
> +    RAILS_LOG_LEVEL: fatal
the log level here is just to rule out that logging was left on at a higher than normal production level. I think it was defaulting to `info` which is a lot of logging that you wouldn't normally have in production. At least, I've never run that level of detail in production

2023-10-17 12:47 UTC, crimson-knight commented
@waghanza I went ahead and added a couple of simple config files for active storage. I'm surprised it's complaining about it though, the original config wasn't using it and I couldn't find anything that was different with the configurations that would require it 🤔

2023-10-17 19:02 UTC, waghanza reviewed
```ruby
Missing `secret_key_base` for 'production' environment, set this string with `bin/rails credentials:edit`
```

I suggest to generate those files for `rails` / `rails-api` and to add
```yaml
    - config/credentials.yml.enc
    - config/master.key
 ```
in _files_ in `ruby/config.yaml`

I suggest also to remove `RAILS_ENV` and `RAILS_LOG_LEVEL` from `ruby/rails` and to set those in `ruby/rails/config.yaml`

Or simply get a look at https://github.com/crimson-knight/web-frameworks/pull/1

2023-10-17 19:05 UTC, waghanza commented on ruby/config.yaml
> +    RAILS_ENV: production
sure, its clearer a good thing to have `RAILS_ENV`, but this is more a rails concern. it should not affect all ruby frameworks

2023-10-24 17:45 UTC, crimson-knight commented
@waghanza I think we are all set now! :)

2023-10-27 07:24 UTC, waghanza approved these changes

2023-10-27 07:24 UTC, merged

2023-10-31 12:44 UTC, waghanza commented
https://web-frameworks-benchmark.netlify.app/result?f=rails-api,rails is much better than previous run https://web-frameworks-benchmark.netlify.app/result?f=rails

thanks @crimson-knight  🎉