[C++] Adding Oat++
the-benchmarker/web-frameworks pull request #6979
Opened 2023-11-25 21:56 UTC by cyrusmsk

Link: https://oatpp.io

Previous issues:
- https://github.com/the-benchmarker/web-frameworks/issues/2426
- https://github.com/the-benchmarker/web-frameworks/issues/659

This PR should implement all 3 endpoints required by the benchmark.
I've tested locally, but after that made some changes in building scripts (config.yaml) so it will be possible to use it in main code. But it is better to test if everything is working properly.

2023-11-25 22:00 UTC, cyrusmsk commented
It worked locally with Cmake 26.. I'm not sure if it will be fine for Cmake 18..
Maybe author of the framework could help with that.

2023-11-26 07:43 UTC, waghanza commented
Thanks @cyrusmsk.

Maybe oat++ is available on Conan. 

cc @lganzzzo

2023-11-26 08:21 UTC, cyrusmsk commented
@waghanza probably it is https://conan.io/center/recipes/oatpp?version=1.3.0

2023-11-27 23:23 UTC, cyrusmsk commented
C++ is just a hell to make normal builds.. I really sorry for people who have to use it..
libevent is not going to work on bookworm - maybe just remove it then? Or fix build..

Regarding oatpp - it was finally built successfully, but had issues in testing:
Failures:

  1) routes POST : /user returns successfully
     Failure/Error: expect(response).to be_a(Net::HTTPSuccess)
       expected #<Net::HTTPNotFound 404 Not Found readbody=true> to be a kind of Net::HTTPSuccess
     # ./.spec/route_spec.rb:40:in `block (3 levels) in <top (required)>'

  2) routes POST : /user returns an empty string
     Failure/Error: expect(response.body.to_s).to be_empty
       expected `"server=oatpp/1.3.0\ncode=404\ndescription=Not Found\nmessage=No mapping for HTTP-method: 'POST', URL: '/user'\n".empty?` to be truthy, got false
     # ./.spec/route_spec.rb:44:in `block (3 levels) in <top (required)>'

Finished in 0.01723 seconds (files took 0.12152 seconds to load)
6 examples, 2 failures

Failed examples:

rspec ./.spec/route_spec.rb:39 # routes POST : /user returns successfully
rspec ./.spec/route_spec.rb:43 # routes POST : /user returns an empty string

@waghanza can you help with that? What does it mean?

2023-11-28 06:33 UTC, waghanza requested changes

2023-11-28 06:33 UTC, waghanza commented on cpp/oatpp/src/controller/MyController.hpp
> +  ENDPOINT("PUT", "/user", putUser) {
Should be post

2023-11-28 13:04 UTC, cyrusmsk commented on cpp/oatpp/src/controller/MyController.hpp
> +  ENDPOINT("PUT", "/user", putUser) {
Right. Thanks

2023-11-28 16:43 UTC, waghanza approved these changes

2023-11-28 16:43 UTC, waghanza commented on cpp/oatpp/config.yaml
> +  version: 1.3.0
```suggestion
  version: 1.3
```

2023-11-28 16:43 UTC, waghanza commented on cpp/oatpp/config.yaml
> +    - git clone --depth=1 https://github.com/oatpp/oatpp.git
```suggestion
    - git clone --depth=1 https://github.com/oatpp/oatpp.git -b 1.3.0
```

2023-11-28 16:43 UTC, merged