[Java] Adding Armeria 1.26.4
the-benchmarker/web-frameworks pull request #7061
Opened 2023-12-18 22:05 UTC by wvuong

2023-12-19 07:58 UTC, waghanza requested changes
Server should listen on `0.0.0.0:3000`

2023-12-19 07:58 UTC, waghanza commented on java/armeria/config.yaml
> +  website: https://armeria.dev/
```suggestion
  website: armeria.dev
```

2023-12-19 07:59 UTC, waghanza commented on java/armeria/pom.xml
> +        <armeria.version>1.26.4</armeria.version>
```suggestion
        <armeria.version>[1.26, 1.27)</armeria.version>
```

2023-12-19 07:59 UTC, waghanza commented
Hi @trustin @minwoox @ikhoon,

We want to include `armeria` in here. Is this OK for you

-------------

Thanks for your contribution @wvuong.

Could log be totally disabled ?

2023-12-19 09:28 UTC, trustin commented
Yes, please. Thank yo for your contribution!

2023-12-19 15:36 UTC, wvuong commented
Addressed your code review comments, thanks!

2023-12-19 15:46 UTC, waghanza requested changes

2023-12-19 15:46 UTC, waghanza commented on java/armeria/src/main/java/benchmark/armeria/BenchmarkApplication.java
> +                .service("/user", (ctx, req) -> EMPTY_HTTP_RESPONSE)
should be a post

2023-12-19 16:59 UTC, waghanza commented
Sorry, CI reveals some errors (500). You should have 3 endpoints :
- GET /
- POST /user
- GET /user/:id (/id is an int)

2023-12-19 17:53 UTC, wvuong commented
No problem.  I goofed up the code and misunderstood your POST comment but I just ran the rspec locally and now it passes.

2023-12-19 20:54 UTC, waghanza commented on java/armeria/pom.xml
> +        <slf4j.version>1.7.36</slf4j.version>
May we use the latest version in maven ? I mean using something dynamic, like + to make sure the build use the latest version available

2023-12-20 05:57 UTC, waghanza approved these changes

2023-12-20 06:05 UTC, merged

2023-12-25 06:38 UTC, waghanza commented
Results available at https://web-frameworks-benchmark.netlify.app/result?f=armeria&l=java