Add Marten web framework
the-benchmarker/web-frameworks pull request #7205
Opened 2024-02-08 02:51 UTC by ellmetha

# Description

This pull request adds [Marten](https://martenframework.com) to the benchmarked Crystal web frameworks. Please let me know if I am missing any configuration files! 🙏

2024-02-08 07:44 UTC, waghanza reviewed
Thanks @ellmetha for your contribution, a small feedback tho

2024-02-08 07:44 UTC, waghanza commented on crystal/marten/config.yml
> +  version: 0.4.0
```suggestion
  version: 0.4
```

2024-02-08 13:24 UTC, ellmetha commented on crystal/marten/config/routes.cr
> +  path "/", RootHandler, name: "root"
Probably not! In Marten, there is a strong assumption that the routing mechanism should only care about request paths. 🙂 

The decision to respond to certain request methods or not is left to the actual [handler](https://martenframework.com/docs/handlers-and-http/introduction#writing-handlers) who can decide to implement corresponding methods (such as `#get`, `#post`, etc). If a handler does not implement a dispatching logic for a given HTTP method, then a "Not allowed" response (405) response is returned automatically by the handler.

2024-02-08 15:00 UTC, waghanza commented on crystal/marten/config/routes.cr
> +  path "/", RootHandler, name: "root"
is it not a security issue @ellmetha ? I mean responding a 405 could be a part of API discovery for an attacker, I would suggest a 404

2024-02-08 15:00 UTC, waghanza requested changes

2024-02-08 15:00 UTC, waghanza commented on crystal/marten/config.yml
sorry, should be `crystal/marten/config.yaml` instead ;-)


CI will trigger if so

2024-02-08 17:43 UTC, ellmetha commented on crystal/marten/config.yml
Ah gotcha!

2024-02-08 17:46 UTC, ellmetha commented on crystal/marten/config/routes.cr
> +  path "/", RootHandler, name: "root"
That's an interesting point. I know that some frameworks have the same mechanism as Marten regarding this aspect (this is the case of Django for example). But making it possible to configure this is something that could be beneficial I think.

2024-02-08 19:06 UTC, waghanza commented on crystal/marten/config/routes.cr
> +  path "/", RootHandler, name: "root"
Also having this into the routing part allows to have a more descriptive file, having at a blink of an eye the existing routes (I mean verbs and URLs)

2024-02-08 19:06 UTC, waghanza approved these changes

2024-02-08 19:06 UTC, merged

2024-02-12 08:43 UTC, waghanza commented
@ellmetha results are updated https://web-frameworks-benchmark.netlify.app/result?l=crystal, but `marten` seems very low