Add PHP 8.3 support
the-benchmarker/web-frameworks pull request #7479
Opened 2024-05-22 19:08 UTC by kpicaza

Hi waghanza,

I just updated Antidot framework dependencies to work with PHP 8.3. Sorry for the delay, but I hadn't realized it wasn't working. 

Thank you very much for your excellent work.

2024-05-22 19:11 UTC, waghanza commented on php/antidot/config.yaml
> +  version: 8.3
```suggestion
```
Default is 8.3

2024-05-22 19:42 UTC, waghanza requested changes
I have the same error @kpicaza 
```php
root@37829aeaa563:/usr/src/app# bin/console serve
php public/index.php 1
php public/index.php 2
php public/index.php 3
php public/index.php 4
php public/index.php 5
php public/index.php 6
php public/index.php 7
php public/index.php 8

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16
Process exited with code 255
Process exited with code 255

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16

Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16
Process exited with code 255
Process exited with code 255
Process exited with code 255
Process exited with code 255
Process exited with code 255
Process exited with code 255
```

2024-05-22 20:32 UTC, kpicaza commented
Looks related to this composer issue https://github.com/composer/composer/issues/11839 It will work by adding as suggested by Seldaek for bitbucket pipelines(Already tested locally):

```yaml
language:
  engines:
    reactphp:
      environment:
        COMPOSER_ALLOW_SUPERUSER: 1
```

2024-05-23 04:31 UTC, waghanza approved these changes

2024-05-23 04:31 UTC, merged