Add Python Panther
the-benchmarker/web-frameworks pull request #7698
Opened 2024-08-23 21:23 UTC by AliRn76

2024-08-24 12:05 UTC, waghanza requested changes
Thanks for your contribution @AliRn76. However, the CI is failing at https://github.com/the-benchmarker/web-frameworks/actions/runs/10532556868/job/29186958118#step:9:12

2024-08-24 21:16 UTC, AliRn76 commented
I'm not sure, but I hope, it passes the ci now :)

2024-08-25 15:37 UTC, waghanza approved these changes

2024-08-25 15:37 UTC, merged

2024-08-26 05:14 UTC, waghanza commented
Results has been updated https://web-frameworks-benchmark.netlify.app/result