use os.availableParallelism()
the-benchmarker/web-frameworks pull request #7836
Opened 2024-10-06 03:56 UTC by mario-huang

2024-10-06 07:27 UTC, waghanza requested changes
Thanks :tada:

Seems that using this function is the way to go https://nodejs.org/api/os.html#oscpus

Could you please replace it on all cluster.ts files ? I'll update results with it for tomorrow

2024-10-06 12:01 UTC, waghanza commented
Btw, thanks for your contribution.

I'll do it

2024-10-06 12:01 UTC, waghanza approved these changes

2024-10-06 12:02 UTC, merged

2024-10-07 04:03 UTC, mario-huang commented
Sure, I opened a PR