Added Total.js v4 and Total.js v5 framework.
the-benchmarker/web-frameworks pull request #7880
Opened 2024-10-21 11:04 UTC by petersirka

2024-10-21 11:38 UTC, waghanza requested changes
Thanks for your contribution :tada:, but maybe we can only include the latest version of one framework.

I understand that having multiple versions could help developers to enhance their framework, but having more than one version of each framework could complexify results.

Could you choose one version? Rather the latest, or even better the lts one, if such approach exist for totaljs

2024-10-21 11:40 UTC, petersirka commented
Thank you. Please keep only `Total5`.

2024-10-21 13:00 UTC, waghanza commented
Could you please proceed ?

I cannot push in PR from master

2024-10-21 19:13 UTC, waghanza requested changes
Could you please rename it in totaljs ?

2024-10-21 19:16 UTC, waghanza commented on javascript/total5/app.js
> +  $.text('Hello world!');
```suggestion
  $.text('');
```

2024-10-21 19:16 UTC, waghanza commented on javascript/total5/config.yaml
> +  version: 0.0.6
```suggestion
  version: 0.0
```

2024-10-22 16:53 UTC, waghanza approved these changes

2024-10-22 16:53 UTC, waghanza commented on javascript/totaljs/config.yaml
> +  version: 0.0.6
```suggestion
  version: 0.0
```

2024-10-22 16:53 UTC, waghanza commented on javascript/totaljs/app.js
> +  $.text('Hello world!');
```suggestion
  $.text('');
```

2024-10-22 16:54 UTC, waghanza requested changes
A route is not correct, I have made a suggestion

2024-10-23 06:03 UTC, waghanza approved these changes

2024-10-23 06:03 UTC, merged