Express bun added
the-benchmarker/web-frameworks pull request #7882
Opened 2024-10-22 12:46 UTC by zahidcakici

`express-bun` added to the project as cluster.

2024-10-22 13:29 UTC, waghanza requested changes

2024-10-22 13:29 UTC, waghanza commented on javascript/express-bun/cluster.ts
Could you homogenize all cluster.ts, I mean for all bun based ?

I am not working with js/ts, I let you decide the most production-ready solution

2024-10-22 15:15 UTC, zahidcakici commented on javascript/express-bun/cluster.ts
It is because express is a npm package and we can't use the bun's build in cluster structure unlike other native bun frameworks. So I think a common structure is not possible right now. At least we can keep the same folder structure and Dockerfile. 

I also stuied the clustering deno case, tried many solutions but couldn't find a proper way. As you know the deno frameworks in repository is running on single instance since even if we run it with pm2 '-i max' command the same problem with npm packages. 

At least bun supports node cluster package unlike deno.

2024-10-22 16:50 UTC, waghanza commented on javascript/express-bun/cluster.ts
Could you add some comments to specify that. I mean the idea is to use some wiki, or other things to have documentation.

Maybe we can specify it in a README in javascript folder.

2024-10-23 06:03 UTC, waghanza approved these changes

2024-10-23 06:03 UTC, merged