Add zig httpz server
the-benchmarker/web-frameworks pull request #7945
Opened 2024-11-12 10:00 UTC by Kayden1412

2024-11-12 13:49 UTC, waghanza requested changes
Thanks for your contribution :tada:

Could you specify GitHub location, and any website for httpz?

2024-11-12 17:01 UTC, waghanza commented
@karlseguin We are going to introduce httpz here. Is this something you are OK with.

We can ping you (not so often) to make sure the implementation is OK

2024-11-12 19:00 UTC, waghanza commented
@Kayden1412 could you use https://github.com/ziglang/docker-zig if it is updated?

2024-11-13 00:52 UTC, karlseguin commented on zig/httpz/src/main.zig
> +    res.keepalive = true;
don't need to set this

2024-11-13 00:52 UTC, karlseguin commented on zig/httpz/src/main.zig
> +    res.keepalive = true;
don't need to set this

2024-11-13 00:53 UTC, karlseguin commented
Sure. 

Current master code is pretty far from 0.13 branch. Maybe when Zig 0.14 is released, we can do an update.

2024-11-13 13:38 UTC, waghanza commented
I have not enough worked with zig to know which image suits best.

The idea is to have an image that you are confident with to go in production, at list  n image close to this goal :stuck_out_tounge:

2024-11-13 13:42 UTC, waghanza commented
I'll add this PR for next round, and monitor zig updates

2024-11-15 17:16 UTC, waghanza approved these changes

2024-11-15 17:16 UTC, merged

2024-11-16 14:53 UTC, waghanza commented
@karlseguin @Kayden1412  I have 
```
thread 26 panic: reached unreachable code
Panicked during a panic. Aborting.
error: the following build command crashed:
/app/.zig-cache/o/3c97310c79e5fa4f1bb00d7c1d5b2ebe/build /usr/bin/zig /app /app/.zig-cache /root/.cache/zig --seed 0x4dd03a9d -Z48d7c4c12cea8f62 -Doptimize=ReleaseFast
```

when trying to compile inside a container with ` zig build -Doptimize=ReleaseFast`

maybe something related to arch, we use aarch to produce results (mac m1)