use pm2 to start durian.js
the-benchmarker/web-frameworks pull request #8072
Opened 2024-12-24 10:28 UTC by mario-huang

pm2-beta seams support bun now, I want to try. If it works, then all bun apps can use it.

2024-12-24 10:54 UTC, waghanza commented
Does this version of pm2 can use deno also ?

2024-12-24 11:07 UTC, mario-huang commented
> Does this version of pm2 can use deno also ?

no, but deno has alternative to pm2 - Pup
https://deno.land/x/pup

2024-12-24 11:08 UTC, mario-huang commented
need help:

Run bundle exec rake config
rake aborted!
NoMethodError: undefined method `unshift' for an instance of String (NoMethodError)

        value.unshift(*value2)
             ^^^^^^^^
/home/runner/work/web-frameworks/web-frameworks/Rakefile:80:in `override_or_merge'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:69:in `block in custom_config'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:66:in `each'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:66:in `custom_config'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:225:in `block ([4](https://github.com/the-benchmarker/web-frameworks/actions/runs/12480482397/job/34831395013?pr=8072#step:6:5) levels) in <top (required)>'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:224:in `each'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:224:in `block (3 levels) in <top (required)>'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:223:in `each'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:223:in `block (2 levels) in <top (required)>'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:217:in `each'
/home/runner/work/web-frameworks/web-frameworks/Rakefile:217:in `block in <top (required)>'
/home/runner/work/web-frameworks/web-frameworks/vendor/bundle/ruby/3.3.0/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle:2[5](https://github.com/the-benchmarker/web-frameworks/actions/runs/12480482397/job/34831395013?pr=8072#step:6:6):in `load'
/opt/hostedtoolcache/Ruby/3.3.6/x64/bin/bundle:25:in `<main>'
Tasks: TOP => config
(See full trace by running task with --trace)
Error: Process completed with exit code 1.

2024-12-24 16:36 UTC, waghanza commented
Will be great to have pup then for deno and pm2 for both bun and node

2024-12-24 16:37 UTC, waghanza commented
Last time I've check pup was not production-ready

2024-12-24 16:43 UTC, waghanza requested changes
Suggestion made will fix CI 😇

Could you also remove bootstrap option in durians config file, and change the one in javascript/config.yaml to bun install --production, in order to make sure Dev dependencies are not use (and to compute build time, in the future)

2024-12-24 16:43 UTC, waghanza commented on javascript/durian.js-fastify/config.yaml
> +    - bun run pm2
This should be a string, not an array.

Also this should be set in javascript/config.yaml file

2024-12-25 01:02 UTC, closed without merging

2024-12-25 01:11 UTC, mario-huang commented
> Suggestion made will fix CI 😇
> 
> Could you also remove bootstrap option in durians config file, and change the one in javascript/config.yaml to bun install --production, in order to make sure Dev dependencies are not use (and to compute build time, in the future)

done that~