chore(deps): update viz to v0.10.0
the-benchmarker/web-frameworks pull request #8089
Opened 2024-12-28 10:40 UTC by fundon

2024-12-28 11:01 UTC, waghanza requested changes

2024-12-28 11:01 UTC, waghanza commented on rust/viz/config.yaml
> +  version: 0.10
```suggestion
  version: '0.10'
```


Otherwise 0.1 will be printed

2024-12-28 11:25 UTC, fundon commented on rust/viz/config.yaml
> +  version: 0.10
thanks

2024-12-28 16:49 UTC, waghanza requested changes

2024-12-28 16:49 UTC, waghanza commented on rust/viz/config.yaml
> +  version: "0.10.0"
```suggestion
  version: "0.10"
```

2024-12-29 06:46 UTC, fundon commented on rust/viz/config.yaml
> +  version: "0.10.0"
does not work

2024-12-29 07:57 UTC, waghanza approved these changes

2024-12-29 07:58 UTC, merged